---
Name: silvershop-reviews-routes
After: '#rootroutes'
---
SilverStripe\Control\Director:
  rules:
    'review': 'SilverShop\Reviews\Control\ReviewInvitationController'
    'shop-review': 'SilverShop\Reviews\Control\ShopReviewController'
